export const ADD_ERROR_POSTS = 'ADD_ERROR_POSTS';
export const CLEAR_ERROR_MESSAGE_POSTS = 'CLEAR_ERROR_MESSAGE_POSTS';
export const IS_LOADING_POSTS = 'IS_LOADING_POSTS';
export const GET_POSTS = 'GET_POSTS';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const UPDATE_POST = 'UPDATE_POST';


